/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUi;
import java.awt.Color;
import java.awt.Dimension;

public class Ahorcado extends javax.swing.JFrame {

   
    public Ahorcado() {
        initComponents();
        setTitle("Ahorcado");// sirve par poner un titulo a la ventana
        setLocationRelativeTo(null);
        setMinimumSize(new Dimension(200,200));
        setDefaultCloseOperation(EXIT_ON_CLOSE);//sirve para cerrar la ventana y terminar la ejecucion
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplnCentro = new javax.swing.JPanel();
        jplnArriba = new javax.swing.JPanel();
        jplnAbajo = new javax.swing.JPanel();
        a = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplnCentro.setLayout(new java.awt.GridLayout(1, 2));
        getContentPane().add(jplnCentro, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jplnArribaLayout = new javax.swing.GroupLayout(jplnArriba);
        jplnArriba.setLayout(jplnArribaLayout);
        jplnArribaLayout.setHorizontalGroup(
            jplnArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jplnArribaLayout.setVerticalGroup(
            jplnArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jplnArriba, java.awt.BorderLayout.PAGE_START);

        jplnAbajo.setLayout(new java.awt.GridLayout(4, 7));

        a.setLabel("A");
        jplnAbajo.add(a);

        jButton2.setLabel("B");
        jplnAbajo.add(jButton2);

        jButton3.setLabel("C");
        jplnAbajo.add(jButton3);

        jButton4.setLabel("D");
        jplnAbajo.add(jButton4);

        jButton5.setLabel("E");
        jplnAbajo.add(jButton5);

        jButton6.setText("F");
        jplnAbajo.add(jButton6);

        jButton7.setLabel("G");
        jplnAbajo.add(jButton7);

        jButton8.setLabel("H");
        jplnAbajo.add(jButton8);

        jButton9.setLabel("I");
        jplnAbajo.add(jButton9);

        jButton10.setLabel("J");
        jplnAbajo.add(jButton10);

        jButton11.setLabel("K");
        jplnAbajo.add(jButton11);

        jButton12.setLabel("L");
        jplnAbajo.add(jButton12);

        jButton13.setLabel("M");
        jplnAbajo.add(jButton13);

        jButton14.setLabel("N");
        jplnAbajo.add(jButton14);

        jButton15.setLabel("Ñ");
        jplnAbajo.add(jButton15);

        jButton16.setLabel("O");
        jplnAbajo.add(jButton16);

        jButton17.setLabel("P");
        jplnAbajo.add(jButton17);

        jButton18.setLabel("Q");
        jplnAbajo.add(jButton18);

        jButton19.setLabel("R");
        jplnAbajo.add(jButton19);

        jButton20.setLabel("S");
        jplnAbajo.add(jButton20);

        jButton21.setLabel("T");
        jplnAbajo.add(jButton21);

        jButton22.setLabel("U");
        jplnAbajo.add(jButton22);

        jButton23.setLabel("V");
        jplnAbajo.add(jButton23);

        jButton24.setLabel("W");
        jplnAbajo.add(jButton24);

        jButton25.setLabel("X");
        jplnAbajo.add(jButton25);

        jButton26.setLabel("Y");
        jplnAbajo.add(jButton26);

        jButton27.setLabel("Z");
        jplnAbajo.add(jButton27);

        getContentPane().add(jplnAbajo, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jplnAbajo;
    private javax.swing.JPanel jplnArriba;
    private javax.swing.JPanel jplnCentro;
    // End of variables declaration//GEN-END:variables
}






